name: joinable_env
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - torchvision=0.20.1
  - pytorch-lightning=2.1.0
  - torchmetrics=1.3.0
  - matplotlib
  - tqdm
  - networkx
  - scipy
  - igl
  - meshplot
  - pip:
    - torch-geometric==2.5.0
    - pysdf
    - trimesh[easy]
